name: unit-test

on:
  push:
    branches:
      - "*"
      - "**"

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Execute tests
        shell: bash
        run: go test -race -cover ./...